package com.gelael.interapp.domain;

/**
 * Created by 15050978 on 3/31/2017.
 */
public class Payment {
//    FHRCID, FHTIPE, FHKCAB, FHNOMD, FHTGLD, FHTGLT, FHJTOP, FHTGLJ, FHKCTR, FHSUPP, FHFPPN, FHFPJK, FHNOMR, FHTNIL, FHTPPN, FHTPPM,
//    FHNBTL, FHDISC, FHLAIN, FHTNLL, FHTPNL, FHTPML, FHNBLL, FHDISL, FHNLNL, FHKETR, FHUSER, FHNOPC, FHNOPL, FHTGUP, FHTGUL, FHTAGP, FHBYRT,
//    FHSTAT,FHFLAG
}
